// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/pb.proto

package org.alking.dynapb;

public final class FooBar {
  private FooBar() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Bar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 lv = 1;</code>
     */
    java.util.List<java.lang.Long> getLvList();
    /**
     * <code>repeated int64 lv = 1;</code>
     */
    int getLvCount();
    /**
     * <code>repeated int64 lv = 1;</code>
     */
    long getLv(int index);

    /**
     * <code>repeated float fv = 2;</code>
     */
    java.util.List<java.lang.Float> getFvList();
    /**
     * <code>repeated float fv = 2;</code>
     */
    int getFvCount();
    /**
     * <code>repeated float fv = 2;</code>
     */
    float getFv(int index);

    /**
     * <code>repeated double dv = 3;</code>
     */
    java.util.List<java.lang.Double> getDvList();
    /**
     * <code>repeated double dv = 3;</code>
     */
    int getDvCount();
    /**
     * <code>repeated double dv = 3;</code>
     */
    double getDv(int index);

    /**
     * <code>repeated bool bv = 4;</code>
     */
    java.util.List<java.lang.Boolean> getBvList();
    /**
     * <code>repeated bool bv = 4;</code>
     */
    int getBvCount();
    /**
     * <code>repeated bool bv = 4;</code>
     */
    boolean getBv(int index);

    /**
     * <code>repeated string sv = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getSvList();
    /**
     * <code>repeated string sv = 5;</code>
     */
    int getSvCount();
    /**
     * <code>repeated string sv = 5;</code>
     */
    java.lang.String getSv(int index);
    /**
     * <code>repeated string sv = 5;</code>
     */
    com.google.protobuf.ByteString
        getSvBytes(int index);
  }
  /**
   * Protobuf type {@code Bar}
   */
  public static final class Bar extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Bar)
      BarOrBuilder {
    // Use Bar.newBuilder() to construct.
    private Bar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Bar(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Bar defaultInstance;
    public static Bar getDefaultInstance() {
      return defaultInstance;
    }

    public Bar getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Bar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                lv_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              lv_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                lv_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                lv_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fv_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              fv_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                fv_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                fv_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                dv_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              dv_.add(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                dv_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                dv_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                bv_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000008;
              }
              bv_.add(input.readBool());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                bv_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                bv_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                sv_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              sv_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          lv_ = java.util.Collections.unmodifiableList(lv_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          fv_ = java.util.Collections.unmodifiableList(fv_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          dv_ = java.util.Collections.unmodifiableList(dv_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          bv_ = java.util.Collections.unmodifiableList(bv_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          sv_ = sv_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.alking.dynapb.FooBar.internal_static_Bar_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.alking.dynapb.FooBar.internal_static_Bar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.alking.dynapb.FooBar.Bar.class, org.alking.dynapb.FooBar.Bar.Builder.class);
    }

    public static com.google.protobuf.Parser<Bar> PARSER =
        new com.google.protobuf.AbstractParser<Bar>() {
      public Bar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bar(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Bar> getParserForType() {
      return PARSER;
    }

    public static final int LV_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> lv_;
    /**
     * <code>repeated int64 lv = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getLvList() {
      return lv_;
    }
    /**
     * <code>repeated int64 lv = 1;</code>
     */
    public int getLvCount() {
      return lv_.size();
    }
    /**
     * <code>repeated int64 lv = 1;</code>
     */
    public long getLv(int index) {
      return lv_.get(index);
    }

    public static final int FV_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> fv_;
    /**
     * <code>repeated float fv = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getFvList() {
      return fv_;
    }
    /**
     * <code>repeated float fv = 2;</code>
     */
    public int getFvCount() {
      return fv_.size();
    }
    /**
     * <code>repeated float fv = 2;</code>
     */
    public float getFv(int index) {
      return fv_.get(index);
    }

    public static final int DV_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Double> dv_;
    /**
     * <code>repeated double dv = 3;</code>
     */
    public java.util.List<java.lang.Double>
        getDvList() {
      return dv_;
    }
    /**
     * <code>repeated double dv = 3;</code>
     */
    public int getDvCount() {
      return dv_.size();
    }
    /**
     * <code>repeated double dv = 3;</code>
     */
    public double getDv(int index) {
      return dv_.get(index);
    }

    public static final int BV_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Boolean> bv_;
    /**
     * <code>repeated bool bv = 4;</code>
     */
    public java.util.List<java.lang.Boolean>
        getBvList() {
      return bv_;
    }
    /**
     * <code>repeated bool bv = 4;</code>
     */
    public int getBvCount() {
      return bv_.size();
    }
    /**
     * <code>repeated bool bv = 4;</code>
     */
    public boolean getBv(int index) {
      return bv_.get(index);
    }

    public static final int SV_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList sv_;
    /**
     * <code>repeated string sv = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSvList() {
      return sv_;
    }
    /**
     * <code>repeated string sv = 5;</code>
     */
    public int getSvCount() {
      return sv_.size();
    }
    /**
     * <code>repeated string sv = 5;</code>
     */
    public java.lang.String getSv(int index) {
      return sv_.get(index);
    }
    /**
     * <code>repeated string sv = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSvBytes(int index) {
      return sv_.getByteString(index);
    }

    private void initFields() {
      lv_ = java.util.Collections.emptyList();
      fv_ = java.util.Collections.emptyList();
      dv_ = java.util.Collections.emptyList();
      bv_ = java.util.Collections.emptyList();
      sv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < lv_.size(); i++) {
        output.writeInt64(1, lv_.get(i));
      }
      for (int i = 0; i < fv_.size(); i++) {
        output.writeFloat(2, fv_.get(i));
      }
      for (int i = 0; i < dv_.size(); i++) {
        output.writeDouble(3, dv_.get(i));
      }
      for (int i = 0; i < bv_.size(); i++) {
        output.writeBool(4, bv_.get(i));
      }
      for (int i = 0; i < sv_.size(); i++) {
        output.writeBytes(5, sv_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < lv_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(lv_.get(i));
        }
        size += dataSize;
        size += 1 * getLvList().size();
      }
      {
        int dataSize = 0;
        dataSize = 4 * getFvList().size();
        size += dataSize;
        size += 1 * getFvList().size();
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDvList().size();
        size += dataSize;
        size += 1 * getDvList().size();
      }
      {
        int dataSize = 0;
        dataSize = 1 * getBvList().size();
        size += dataSize;
        size += 1 * getBvList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sv_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(sv_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getSvList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.alking.dynapb.FooBar.Bar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Bar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.alking.dynapb.FooBar.Bar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alking.dynapb.FooBar.Bar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.alking.dynapb.FooBar.Bar prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Bar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Bar)
        org.alking.dynapb.FooBar.BarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.alking.dynapb.FooBar.internal_static_Bar_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.alking.dynapb.FooBar.internal_static_Bar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.alking.dynapb.FooBar.Bar.class, org.alking.dynapb.FooBar.Bar.Builder.class);
      }

      // Construct using org.alking.dynapb.FooBar.Bar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        fv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        dv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        bv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        sv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.alking.dynapb.FooBar.internal_static_Bar_descriptor;
      }

      public org.alking.dynapb.FooBar.Bar getDefaultInstanceForType() {
        return org.alking.dynapb.FooBar.Bar.getDefaultInstance();
      }

      public org.alking.dynapb.FooBar.Bar build() {
        org.alking.dynapb.FooBar.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.alking.dynapb.FooBar.Bar buildPartial() {
        org.alking.dynapb.FooBar.Bar result = new org.alking.dynapb.FooBar.Bar(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          lv_ = java.util.Collections.unmodifiableList(lv_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.lv_ = lv_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          fv_ = java.util.Collections.unmodifiableList(fv_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fv_ = fv_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          dv_ = java.util.Collections.unmodifiableList(dv_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.dv_ = dv_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          bv_ = java.util.Collections.unmodifiableList(bv_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.bv_ = bv_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          sv_ = sv_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.sv_ = sv_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.alking.dynapb.FooBar.Bar) {
          return mergeFrom((org.alking.dynapb.FooBar.Bar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.alking.dynapb.FooBar.Bar other) {
        if (other == org.alking.dynapb.FooBar.Bar.getDefaultInstance()) return this;
        if (!other.lv_.isEmpty()) {
          if (lv_.isEmpty()) {
            lv_ = other.lv_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLvIsMutable();
            lv_.addAll(other.lv_);
          }
          onChanged();
        }
        if (!other.fv_.isEmpty()) {
          if (fv_.isEmpty()) {
            fv_ = other.fv_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFvIsMutable();
            fv_.addAll(other.fv_);
          }
          onChanged();
        }
        if (!other.dv_.isEmpty()) {
          if (dv_.isEmpty()) {
            dv_ = other.dv_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDvIsMutable();
            dv_.addAll(other.dv_);
          }
          onChanged();
        }
        if (!other.bv_.isEmpty()) {
          if (bv_.isEmpty()) {
            bv_ = other.bv_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureBvIsMutable();
            bv_.addAll(other.bv_);
          }
          onChanged();
        }
        if (!other.sv_.isEmpty()) {
          if (sv_.isEmpty()) {
            sv_ = other.sv_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSvIsMutable();
            sv_.addAll(other.sv_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.alking.dynapb.FooBar.Bar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.alking.dynapb.FooBar.Bar) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> lv_ = java.util.Collections.emptyList();
      private void ensureLvIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          lv_ = new java.util.ArrayList<java.lang.Long>(lv_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getLvList() {
        return java.util.Collections.unmodifiableList(lv_);
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public int getLvCount() {
        return lv_.size();
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public long getLv(int index) {
        return lv_.get(index);
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public Builder setLv(
          int index, long value) {
        ensureLvIsMutable();
        lv_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public Builder addLv(long value) {
        ensureLvIsMutable();
        lv_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public Builder addAllLv(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lv_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 lv = 1;</code>
       */
      public Builder clearLv() {
        lv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> fv_ = java.util.Collections.emptyList();
      private void ensureFvIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fv_ = new java.util.ArrayList<java.lang.Float>(fv_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getFvList() {
        return java.util.Collections.unmodifiableList(fv_);
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public int getFvCount() {
        return fv_.size();
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public float getFv(int index) {
        return fv_.get(index);
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public Builder setFv(
          int index, float value) {
        ensureFvIsMutable();
        fv_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public Builder addFv(float value) {
        ensureFvIsMutable();
        fv_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public Builder addAllFv(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureFvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fv_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float fv = 2;</code>
       */
      public Builder clearFv() {
        fv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> dv_ = java.util.Collections.emptyList();
      private void ensureDvIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          dv_ = new java.util.ArrayList<java.lang.Double>(dv_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getDvList() {
        return java.util.Collections.unmodifiableList(dv_);
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public int getDvCount() {
        return dv_.size();
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public double getDv(int index) {
        return dv_.get(index);
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public Builder setDv(
          int index, double value) {
        ensureDvIsMutable();
        dv_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public Builder addDv(double value) {
        ensureDvIsMutable();
        dv_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public Builder addAllDv(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dv_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double dv = 3;</code>
       */
      public Builder clearDv() {
        dv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> bv_ = java.util.Collections.emptyList();
      private void ensureBvIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          bv_ = new java.util.ArrayList<java.lang.Boolean>(bv_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public java.util.List<java.lang.Boolean>
          getBvList() {
        return java.util.Collections.unmodifiableList(bv_);
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public int getBvCount() {
        return bv_.size();
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public boolean getBv(int index) {
        return bv_.get(index);
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public Builder setBv(
          int index, boolean value) {
        ensureBvIsMutable();
        bv_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public Builder addBv(boolean value) {
        ensureBvIsMutable();
        bv_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public Builder addAllBv(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureBvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bv_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool bv = 4;</code>
       */
      public Builder clearBv() {
        bv_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList sv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSvIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          sv_ = new com.google.protobuf.LazyStringArrayList(sv_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSvList() {
        return sv_.getUnmodifiableView();
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public int getSvCount() {
        return sv_.size();
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public java.lang.String getSv(int index) {
        return sv_.get(index);
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSvBytes(int index) {
        return sv_.getByteString(index);
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public Builder setSv(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSvIsMutable();
        sv_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public Builder addSv(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSvIsMutable();
        sv_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public Builder addAllSv(
          java.lang.Iterable<java.lang.String> values) {
        ensureSvIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sv_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public Builder clearSv() {
        sv_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sv = 5;</code>
       */
      public Builder addSvBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSvIsMutable();
        sv_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Bar)
    }

    static {
      defaultInstance = new Bar(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Bar)
  }

  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Foo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 var_int = 1;</code>
     */
    boolean hasVarInt();
    /**
     * <code>optional int64 var_int = 1;</code>
     */
    long getVarInt();

    /**
     * <code>optional float var_float = 2;</code>
     */
    boolean hasVarFloat();
    /**
     * <code>optional float var_float = 2;</code>
     */
    float getVarFloat();

    /**
     * <code>optional double var_double = 3;</code>
     */
    boolean hasVarDouble();
    /**
     * <code>optional double var_double = 3;</code>
     */
    double getVarDouble();

    /**
     * <code>optional bool var_bool = 4;</code>
     */
    boolean hasVarBool();
    /**
     * <code>optional bool var_bool = 4;</code>
     */
    boolean getVarBool();

    /**
     * <code>optional string var_string = 5;</code>
     */
    boolean hasVarString();
    /**
     * <code>optional string var_string = 5;</code>
     */
    java.lang.String getVarString();
    /**
     * <code>optional string var_string = 5;</code>
     */
    com.google.protobuf.ByteString
        getVarStringBytes();
  }
  /**
   * Protobuf type {@code Foo}
   */
  public static final class Foo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Foo)
      FooOrBuilder {
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Foo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Foo defaultInstance;
    public static Foo getDefaultInstance() {
      return defaultInstance;
    }

    public Foo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Foo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              varInt_ = input.readInt64();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              varFloat_ = input.readFloat();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              varDouble_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              varBool_ = input.readBool();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              varString_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.alking.dynapb.FooBar.internal_static_Foo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.alking.dynapb.FooBar.internal_static_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.alking.dynapb.FooBar.Foo.class, org.alking.dynapb.FooBar.Foo.Builder.class);
    }

    public static com.google.protobuf.Parser<Foo> PARSER =
        new com.google.protobuf.AbstractParser<Foo>() {
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VAR_INT_FIELD_NUMBER = 1;
    private long varInt_;
    /**
     * <code>optional int64 var_int = 1;</code>
     */
    public boolean hasVarInt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 var_int = 1;</code>
     */
    public long getVarInt() {
      return varInt_;
    }

    public static final int VAR_FLOAT_FIELD_NUMBER = 2;
    private float varFloat_;
    /**
     * <code>optional float var_float = 2;</code>
     */
    public boolean hasVarFloat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float var_float = 2;</code>
     */
    public float getVarFloat() {
      return varFloat_;
    }

    public static final int VAR_DOUBLE_FIELD_NUMBER = 3;
    private double varDouble_;
    /**
     * <code>optional double var_double = 3;</code>
     */
    public boolean hasVarDouble() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double var_double = 3;</code>
     */
    public double getVarDouble() {
      return varDouble_;
    }

    public static final int VAR_BOOL_FIELD_NUMBER = 4;
    private boolean varBool_;
    /**
     * <code>optional bool var_bool = 4;</code>
     */
    public boolean hasVarBool() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool var_bool = 4;</code>
     */
    public boolean getVarBool() {
      return varBool_;
    }

    public static final int VAR_STRING_FIELD_NUMBER = 5;
    private java.lang.Object varString_;
    /**
     * <code>optional string var_string = 5;</code>
     */
    public boolean hasVarString() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string var_string = 5;</code>
     */
    public java.lang.String getVarString() {
      java.lang.Object ref = varString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          varString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string var_string = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVarStringBytes() {
      java.lang.Object ref = varString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        varString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      varInt_ = 0L;
      varFloat_ = 0F;
      varDouble_ = 0D;
      varBool_ = false;
      varString_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, varInt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, varFloat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, varDouble_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, varBool_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getVarStringBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, varInt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, varFloat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, varDouble_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, varBool_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getVarStringBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.alking.dynapb.FooBar.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.alking.dynapb.FooBar.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.alking.dynapb.FooBar.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.alking.dynapb.FooBar.Foo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Foo)
        org.alking.dynapb.FooBar.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.alking.dynapb.FooBar.internal_static_Foo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.alking.dynapb.FooBar.internal_static_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.alking.dynapb.FooBar.Foo.class, org.alking.dynapb.FooBar.Foo.Builder.class);
      }

      // Construct using org.alking.dynapb.FooBar.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        varInt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        varFloat_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        varDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        varBool_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        varString_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.alking.dynapb.FooBar.internal_static_Foo_descriptor;
      }

      public org.alking.dynapb.FooBar.Foo getDefaultInstanceForType() {
        return org.alking.dynapb.FooBar.Foo.getDefaultInstance();
      }

      public org.alking.dynapb.FooBar.Foo build() {
        org.alking.dynapb.FooBar.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.alking.dynapb.FooBar.Foo buildPartial() {
        org.alking.dynapb.FooBar.Foo result = new org.alking.dynapb.FooBar.Foo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.varInt_ = varInt_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.varFloat_ = varFloat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.varDouble_ = varDouble_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.varBool_ = varBool_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.varString_ = varString_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.alking.dynapb.FooBar.Foo) {
          return mergeFrom((org.alking.dynapb.FooBar.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.alking.dynapb.FooBar.Foo other) {
        if (other == org.alking.dynapb.FooBar.Foo.getDefaultInstance()) return this;
        if (other.hasVarInt()) {
          setVarInt(other.getVarInt());
        }
        if (other.hasVarFloat()) {
          setVarFloat(other.getVarFloat());
        }
        if (other.hasVarDouble()) {
          setVarDouble(other.getVarDouble());
        }
        if (other.hasVarBool()) {
          setVarBool(other.getVarBool());
        }
        if (other.hasVarString()) {
          bitField0_ |= 0x00000010;
          varString_ = other.varString_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.alking.dynapb.FooBar.Foo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.alking.dynapb.FooBar.Foo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long varInt_ ;
      /**
       * <code>optional int64 var_int = 1;</code>
       */
      public boolean hasVarInt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 var_int = 1;</code>
       */
      public long getVarInt() {
        return varInt_;
      }
      /**
       * <code>optional int64 var_int = 1;</code>
       */
      public Builder setVarInt(long value) {
        bitField0_ |= 0x00000001;
        varInt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 var_int = 1;</code>
       */
      public Builder clearVarInt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        varInt_ = 0L;
        onChanged();
        return this;
      }

      private float varFloat_ ;
      /**
       * <code>optional float var_float = 2;</code>
       */
      public boolean hasVarFloat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float var_float = 2;</code>
       */
      public float getVarFloat() {
        return varFloat_;
      }
      /**
       * <code>optional float var_float = 2;</code>
       */
      public Builder setVarFloat(float value) {
        bitField0_ |= 0x00000002;
        varFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float var_float = 2;</code>
       */
      public Builder clearVarFloat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        varFloat_ = 0F;
        onChanged();
        return this;
      }

      private double varDouble_ ;
      /**
       * <code>optional double var_double = 3;</code>
       */
      public boolean hasVarDouble() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double var_double = 3;</code>
       */
      public double getVarDouble() {
        return varDouble_;
      }
      /**
       * <code>optional double var_double = 3;</code>
       */
      public Builder setVarDouble(double value) {
        bitField0_ |= 0x00000004;
        varDouble_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double var_double = 3;</code>
       */
      public Builder clearVarDouble() {
        bitField0_ = (bitField0_ & ~0x00000004);
        varDouble_ = 0D;
        onChanged();
        return this;
      }

      private boolean varBool_ ;
      /**
       * <code>optional bool var_bool = 4;</code>
       */
      public boolean hasVarBool() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool var_bool = 4;</code>
       */
      public boolean getVarBool() {
        return varBool_;
      }
      /**
       * <code>optional bool var_bool = 4;</code>
       */
      public Builder setVarBool(boolean value) {
        bitField0_ |= 0x00000008;
        varBool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool var_bool = 4;</code>
       */
      public Builder clearVarBool() {
        bitField0_ = (bitField0_ & ~0x00000008);
        varBool_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object varString_ = "";
      /**
       * <code>optional string var_string = 5;</code>
       */
      public boolean hasVarString() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string var_string = 5;</code>
       */
      public java.lang.String getVarString() {
        java.lang.Object ref = varString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            varString_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string var_string = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVarStringBytes() {
        java.lang.Object ref = varString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          varString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string var_string = 5;</code>
       */
      public Builder setVarString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        varString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string var_string = 5;</code>
       */
      public Builder clearVarString() {
        bitField0_ = (bitField0_ & ~0x00000010);
        varString_ = getDefaultInstance().getVarString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string var_string = 5;</code>
       */
      public Builder setVarStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        varString_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Foo)
    }

    static {
      defaultInstance = new Foo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Foo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Bar_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Bar_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Foo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Foo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016proto/pb.proto\"A\n\003Bar\022\n\n\002lv\030\001 \003(\003\022\n\n\002f" +
      "v\030\002 \003(\002\022\n\n\002dv\030\003 \003(\001\022\n\n\002bv\030\004 \003(\010\022\n\n\002sv\030\005 " +
      "\003(\t\"c\n\003Foo\022\017\n\007var_int\030\001 \001(\003\022\021\n\tvar_float" +
      "\030\002 \001(\002\022\022\n\nvar_double\030\003 \001(\001\022\020\n\010var_bool\030\004" +
      " \001(\010\022\022\n\nvar_string\030\005 \001(\tB\033\n\021org.alking.d" +
      "ynapbB\006FooBar"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Bar_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Bar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Bar_descriptor,
        new java.lang.String[] { "Lv", "Fv", "Dv", "Bv", "Sv", });
    internal_static_Foo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Foo_descriptor,
        new java.lang.String[] { "VarInt", "VarFloat", "VarDouble", "VarBool", "VarString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
